version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the React app...
      - npm run build
  post_build:
    commands:
      - echo Copying Deploy Files to dist...
      - cp Dockerfile dist
      - cp appspec.yml dist
      - cp -r scripts dist
      - echo Build completed successfully.

artifacts:
  files:
    - "**/*"
  base-directory: dist

cache:
  paths:
    - "node_modules/**/*"
